#!/usr/bin/env python3
"""
Reintento automatico para envios de WhatsApp ante errores
transitorios de Meta (is_transient: true / code: 2, 'retry your
request later'). Hasta 2 reintentos con espera creciente (1s, 2s).
Esto deberia reducir respuestas perdidas por hiccups pasajeros de
la API de Meta, tanto para texto como para fotos de servicios.

Ejecutar desde la raiz del repo (carpeta que contiene 'src'):
    python3 apply_whatsapp_retry_transient.py
"""

import base64
from pathlib import Path

WHATSAPP_LIB_B64 = """Y29uc3QgR1JBUEhfQVBJX1ZFUlNJT04gPSAndjIxLjAnCmNvbnN0IE1BWF9SRVRSSUVTID0gMgpjb25zdCBSRVRSWV9ERUxBWV9NUyA9IDEwMDAKCmZ1bmN0aW9uIGlzVHJhbnNpZW50RXJyb3IoZXJyVGV4dDogc3RyaW5nKTogYm9vbGVhbiB7CiAgdHJ5IHsKICAgIGNvbnN0IHBhcnNlZCA9IEpTT04ucGFyc2UoZXJyVGV4dCkKICAgIHJldHVybiBwYXJzZWQ/LmVycm9yPy5pc190cmFuc2llbnQgPT09IHRydWUgfHwgcGFyc2VkPy5lcnJvcj8uY29kZSA9PT0gMgogIH0gY2F0Y2ggewogICAgcmV0dXJuIGZhbHNlCiAgfQp9CgovKioKICogUE9TVCBnZW5lcmljbyBhbCBlbmRwb2ludCAvbWVzc2FnZXMgZGUgV2hhdHNBcHAgQ2xvdWQgQVBJLCBjb24gcmVpbnRlbnRvCiAqIGF1dG9tYXRpY28gY3VhbmRvIE1ldGEgZGV2dWVsdmUgdW4gZXJyb3IgdHJhbnNpdG9yaW8KICogKGlzX3RyYW5zaWVudDogdHJ1ZSAvIGNvZGU6IDIsICJyZXRyeSB5b3VyIHJlcXVlc3QgbGF0ZXIiKS4KICovCmFzeW5jIGZ1bmN0aW9uIHBvc3RNZXNzYWdlKHBob25lTnVtYmVySWQ6IHN0cmluZywgYWNjZXNzVG9rZW46IHN0cmluZywgcGF5bG9hZDogb2JqZWN0LCBsYWJlbDogc3RyaW5nKSB7CiAgbGV0IGxhc3RFcnJvciA9ICcnCgogIGZvciAobGV0IGF0dGVtcHQgPSAwOyBhdHRlbXB0IDw9IE1BWF9SRVRSSUVTOyBhdHRlbXB0KyspIHsKICAgIGNvbnN0IHJlcyA9IGF3YWl0IGZldGNoKGBodHRwczovL2dyYXBoLmZhY2Vib29rLmNvbS8ke0dSQVBIX0FQSV9WRVJTSU9OfS8ke3Bob25lTnVtYmVySWR9L21lc3NhZ2VzYCwgewogICAgICBtZXRob2Q6ICdQT1NUJywKICAgICAgaGVhZGVyczogewogICAgICAgIEF1dGhvcml6YXRpb246IGBCZWFyZXIgJHthY2Nlc3NUb2tlbn1gLAogICAgICAgICdDb250ZW50LVR5cGUnOiAnYXBwbGljYXRpb24vanNvbicsCiAgICAgIH0sCiAgICAgIGJvZHk6IEpTT04uc3RyaW5naWZ5KHBheWxvYWQpLAogICAgfSkKCiAgICBpZiAocmVzLm9rKSByZXR1cm4gcmVzLmpzb24oKQoKICAgIGxhc3RFcnJvciA9IGF3YWl0IHJlcy50ZXh0KCkKCiAgICBpZiAoYXR0ZW1wdCA8IE1BWF9SRVRSSUVTICYmIGlzVHJhbnNpZW50RXJyb3IobGFzdEVycm9yKSkgewogICAgICBjb25zb2xlLndhcm4oYFt3aGF0c2FwcF0gJHtsYWJlbH0gZXJyb3IgdHJhbnNpdG9yaW8sIHJlaW50ZW50YW5kbyAoaW50ZW50byAke2F0dGVtcHQgKyAxfS8ke01BWF9SRVRSSUVTfSlgKQogICAgICBhd2FpdCBuZXcgUHJvbWlzZSgocikgPT4gc2V0VGltZW91dChyLCBSRVRSWV9ERUxBWV9NUyAqIChhdHRlbXB0ICsgMSkpKQogICAgICBjb250aW51ZQogICAgfQoKICAgIHRocm93IG5ldyBFcnJvcihgJHtsYWJlbH0gZmFpbGVkICgke3Jlcy5zdGF0dXN9KTogJHtsYXN0RXJyb3J9YCkKICB9CgogIHRocm93IG5ldyBFcnJvcihgJHtsYWJlbH0gZmFpbGVkOiAke2xhc3RFcnJvcn1gKQp9CgovKioKICogRW52aWEgdW4gbWVuc2FqZSBkZSB0ZXh0byBwb3IgV2hhdHNBcHAgQ2xvdWQgQVBJLgogKiBwaG9uZU51bWJlcklkIHkgYWNjZXNzVG9rZW4gdmllbmVuIGRlIG9yZ2FuaXphdGlvbnMud2hhdHNhcHBfcGhvbmVfbnVtYmVyX2lkCiAqIHkgb3JnYW5pemF0aW9ucy53aGF0c2FwcF9hY2Nlc3NfdG9rZW4gKGNvbmZpZ3VyYWRvcyBkZXNkZSBTZXR0aW5ncykuCiAqLwpleHBvcnQgYXN5bmMgZnVuY3Rpb24gc2VuZFdoYXRzQXBwTWVzc2FnZShwaG9uZU51bWJlcklkOiBzdHJpbmcsIGFjY2Vzc1Rva2VuOiBzdHJpbmcsIHRvOiBzdHJpbmcsIHRleHQ6IHN0cmluZykgewogIHJldHVybiBwb3N0TWVzc2FnZSgKICAgIHBob25lTnVtYmVySWQsCiAgICBhY2Nlc3NUb2tlbiwKICAgIHsKICAgICAgbWVzc2FnaW5nX3Byb2R1Y3Q6ICd3aGF0c2FwcCcsCiAgICAgIHRvLAogICAgICB0eXBlOiAndGV4dCcsCiAgICAgIHRleHQ6IHsgYm9keTogdGV4dCB9LAogICAgfSwKICAgICdXaGF0c0FwcCBzZW5kJwogICkKfQoKLyoqCiAqIEVudmlhIHVuIG1lbnNhamUgZGUgaW1hZ2VuIHBvciBXaGF0c0FwcCBDbG91ZCBBUEksIHJlZmVyZW5jaWFuZG8gdW5hIFVSTAogKiBwdWJsaWNhIChlai4gbGEgaW1hZ2VuIGRlIHVuIHNlcnZpY2lvIGVuIFN1cGFiYXNlIFN0b3JhZ2UpLgogKi8KZXhwb3J0IGFzeW5jIGZ1bmN0aW9uIHNlbmRXaGF0c0FwcEltYWdlKHBob25lTnVtYmVySWQ6IHN0cmluZywgYWNjZXNzVG9rZW46IHN0cmluZywgdG86IHN0cmluZywgaW1hZ2VVcmw6IHN0cmluZywgY2FwdGlvbj86IHN0cmluZykgewogIHJldHVybiBwb3N0TWVzc2FnZSgKICAgIHBob25lTnVtYmVySWQsCiAgICBhY2Nlc3NUb2tlbiwKICAgIHsKICAgICAgbWVzc2FnaW5nX3Byb2R1Y3Q6ICd3aGF0c2FwcCcsCiAgICAgIHRvLAogICAgICB0eXBlOiAnaW1hZ2UnLAogICAgICBpbWFnZTogY2FwdGlvbiA/IHsgbGluazogaW1hZ2VVcmwsIGNhcHRpb24gfSA6IHsgbGluazogaW1hZ2VVcmwgfSwKICAgIH0sCiAgICAnV2hhdHNBcHAgaW1hZ2Ugc2VuZCcKICApCn0K"""

def main():
    p = Path("src/lib/whatsapp.ts")
    p.write_bytes(base64.b64decode(WHATSAPP_LIB_B64))
    print(f"escrito: {p} ({p.stat().st_size} bytes)")
    print()
    print("Listo. Luego:")
    print("  git add -A")
    print("  git commit -m 'WhatsApp: reintento ante errores transitorios de Meta'")
    print("  git push")

if __name__ == "__main__":
    main()